#!/usr/bin/env bash
# Reads ../.env.local + ../workers/.dev.vars and writes terraform.tfvars
# (gitignored). Maps env keys → terraform var names.
#
# Source order:
#   1. .env.local       — server-rs-only keys (SONIOX, TUNNEL_*)
#   2. workers/.dev.vars — Workers-canonical shared secrets (JWT, INTERNAL,
#                         GOOGLE_*, ELEVENLABS). Sourced LAST so any
#                         overlap resolves to the wrangler-dev value.

set -euo pipefail
cd "$(dirname "$0")"

ENV_FILE="../.env.local"
DEV_VARS="../workers/.dev.vars"

if [[ ! -f "$ENV_FILE" && ! -f "$DEV_VARS" && "${BRIVVA_INFISICAL:-}" != "1" ]]; then
    echo "ERROR: neither $ENV_FILE nor $DEV_VARS exists"
    exit 1
fi

set -a
if [[ -f "$ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    . "$ENV_FILE"
fi
if [[ -f "$DEV_VARS" ]]; then
    # shellcheck disable=SC1090
    . "$DEV_VARS"
fi
set +a

# Shell-escape a string as a terraform string literal.
tf_str() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

# Transition fallback: prefer ELEVENLABS_API_KEY (canonical), fall back to
# the legacy TTS_API_KEY name if someone hasn't migrated yet. Drop the
# fallback once every env is on the canonical name.
ELEVENLABS_API_KEY="${ELEVENLABS_API_KEY:-${TTS_API_KEY:-}}"

{
    echo "# Generated by load-env.sh — DO NOT COMMIT"
    echo "soniox_api_key       = \"$(tf_str "${SONIOX_API_KEY:-}")\""
    echo "elevenlabs_api_key   = \"$(tf_str "${ELEVENLABS_API_KEY:-}")\""
    echo "google_client_id     = \"$(tf_str "${GOOGLE_CLIENT_ID:-}")\""
    echo "google_client_secret = \"$(tf_str "${GOOGLE_CLIENT_SECRET:-}")\""
    echo "tunnel_creds         = \"$(tf_str "${TUNNEL_CREDS:-}")\""
    echo "tunnel_id            = \"$(tf_str "${TUNNEL_ID:-}")\""
    echo "jwt_secret           = \"$(tf_str "${JWT_SECRET:-}")\""
    echo "internal_secret      = \"$(tf_str "${INTERNAL_SECRET:-}")\""
} > terraform.tfvars

echo "wrote terraform.tfvars"
[[ -z "${SONIOX_API_KEY:-}" ]]      && echo "  WARN: SONIOX_API_KEY empty"
[[ -z "${ELEVENLABS_API_KEY:-}" ]]  && echo "  WARN: ELEVENLABS_API_KEY empty"
[[ -z "${TUNNEL_CREDS:-}" ]]        && echo "  INFO: TUNNEL_CREDS empty → cloudflared sidecar will be disabled"
exit 0
