#!/usr/bin/env bash
# Reads ../.env.local and writes terraform.tfvars (gitignored).
# Maps .env keys → terraform var names.

set -euo pipefail
cd "$(dirname "$0")"

ENV_FILE="../.env.local"
if [[ ! -f "$ENV_FILE" ]]; then
    echo "ERROR: $ENV_FILE not found"
    exit 1
fi

# shellcheck disable=SC1090
set -a
. "$ENV_FILE"
set +a

# Shell-escape a string as a terraform string literal.
tf_str() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

{
    echo "# Generated by load-env.sh — DO NOT COMMIT"
    echo "soniox_api_key       = \"$(tf_str "${SONIOX_API_KEY:-}")\""
    echo "elevenlabs_api_key   = \"$(tf_str "${TTS_API_KEY:-}")\""
    echo "google_client_id     = \"$(tf_str "${GOOGLE_CLIENT_ID:-}")\""
    echo "google_client_secret = \"$(tf_str "${GOOGLE_CLIENT_SECRET:-}")\""
    echo "tunnel_creds         = \"$(tf_str "${TUNNEL_CREDS:-}")\""
    echo "tunnel_id            = \"$(tf_str "${TUNNEL_ID:-}")\""
    echo "jwt_secret           = \"$(tf_str "${JWT_SECRET:-}")\""
    echo "internal_secret      = \"$(tf_str "${INTERNAL_SECRET:-}")\""
} > terraform.tfvars

echo "wrote terraform.tfvars"
[[ -z "${SONIOX_API_KEY:-}" ]]    && echo "  WARN: SONIOX_API_KEY empty"
[[ -z "${TTS_API_KEY:-}" ]]       && echo "  WARN: TTS_API_KEY empty (mapped to elevenlabs_api_key)"
[[ -z "${TUNNEL_CREDS:-}" ]]      && echo "  INFO: TUNNEL_CREDS empty → cloudflared sidecar will be disabled"
exit 0
