#!/usr/bin/env bash
# Writes non-secret Terraform overrides to terraform.tfvars (gitignored).
# Runtime secret values are synced from Infisical into AWS Secrets Manager;
# Terraform only owns the secret container/IAM wiring.

set -euo pipefail
cd "$(dirname "$0")"

ENV_FILE="../.env.local"

if [[ -f "$ENV_FILE" ]]; then
    set -a
    # shellcheck disable=SC1090
    . "$ENV_FILE"
    set +a
fi

# Shell-escape a string as a terraform string literal.
tf_str() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

{
    echo "# Generated by load-env.sh — DO NOT COMMIT"
    echo "enable_cloudflared   = ${ENABLE_CLOUDFLARED:-true}"
    echo "tunnel_id            = \"$(tf_str "${TUNNEL_ID:-}")\""
} > terraform.tfvars

echo "wrote terraform.tfvars"
[[ -z "${TUNNEL_ID:-}" ]] && echo "  WARN: TUNNEL_ID empty → cloudflared sidecar will be disabled"
exit 0
